src/utils.c
Currently if toolchain has implementation of explicit_bzero() and so
HAVE_EXPLICIT_BZERO gets defined during configuration compilation will
fail that way:
------------------------------------>8------------------------------
utils.c: In function 'pure_memzero':
utils.c:49:1: error: expected declaration or statement at end of input
}
^
------------------------------------>8------------------------------
That happens because closing "#endif" is put 1 line below than really
meant.
Signed-off-by: Alexey Brodkin <abrodkin@synopsys.com>
=> Fix building in case of HAVE_EXPLICIT_BZERO

man/pure-authd.8.in
=> Fix typo in pure-authd manual page found by Jon Daley (Debian bug #652936)

AUTHORS, ChangeLog, FAQ, NEWS, README, README.Contrib, README.Virtual-Users, contrib/pure-stat.pl, man/pure-ftpd.8.in, man/pure-ftpwho.8.in, pure-ftpd.conf.in, puredb/README, src/diraliases.c, src/fakesnprintf.c, src/log_pam.c, src/pure-ftpwho.c
patch contains some spelling fixes ( just in comments ) as found by a bot ( https://github.com/ka7/misspell_fixer ). Any upcoming License changes (e.g. GPL2 to GPL3+) are hereby granted.
=> spelling fixes

src/ls.c
The STAT command output get sent unencrypted on the control socket (thus
breaking the proper TLS stream) unless the client enabled private protection
for the data socket via the PROT command.
The problem is easly reproducible:
$ openssl s_client -connect 127.0.0.1:1256 -starttls ftp
220 You will be disconnected after 15 minutes of inactivity.
user
230 Anonymous user logged in
stat a
140316490120920:error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:s3_pkt.c:362:
OpenSSL s_client throws an error since pure-ftpd replied "213-STAT" directly
on the TCP stream, in plain text, instead of witing it inside the TLS tunnel.
The current code also allows a null pointer dereference: if you start TLS via
AUTH TLS, then login, enable data socket protection (PROT P) and end TLS on
control …
=> Fix STAT on TLS connections

pure-ftpd.conf.in
Hello,
this is small path fixing
we don't need this '/etc' in path because 
sysconfdir = prefix + '/etc'
=> path fixing

configure.ac
Signed-off-by: Bernd Kuhls <bernd.kuhls@t-online.de>
[Retrieved (and slightly updated) from
https://git.buildroot.net/buildroot/tree/package/pure-ftpd/0001-cross.patch]
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
=> Do not include host paths when cross-compiling.

src/ftp_parser.c
Instead of disconnecting the client when a TLS session has not been established yet, allow the client to gracefully "fail-over" to an encrypted session (by sending an AUTH TLS command). This behavior also corresponds with the error code (421) which belongs to "4xx Transient Negative Completion reply" category, which indicates that the error condition is temporary.
=> Allow client to gracefully fail-over for non-TLS sessions

.gitignore, configure.ac
The AM_PROG_AR macro was added in Automake 1.11.2 thus the minimum
Automake version is increased.
Downstream-Bug: https://bugs.gentoo.org/721242
=> configure: Use AM_PROG_AR to improve portability

src/ftpd.c
Make with `--without-ascii` fails due to invalid syntax. Just moved `#ifndef WITHOUT_ASCII` one line up.
=> Make --without-ascii fails

src/ftpd.c
While altering `Feat` array, we leave out `\r` which raises error because we get (* is cursor) -
> ...
> _ESTA
> _PASV
> *EPSV
instead of
> ...
> _ESTA
> _PASV
> _EPSV*
in the later stage new-line is added when clubbing FEAT and remaining message.
Tested on https://ftptest.net (with -P parameter i.e. force_passive_ip) before and after this change.
=> Error: Carriage return without line feed received

src/ftpd_p.h, src/simpleconf_ftpd.h
I had some trouble to identify unsupported runtime-options, when using a configuration file, which did not match with the build-flags.
For example: I set `UserBandwidth  123` within `pure-ftpd.conf`, but build was done without `./configure --with-throttling`. When starting the server only `421 Unknown run-time option` comes up, not naming unknown option.
* Support for "Bonjour"-runtime-option added to configuration file.
* Strip out runtime-options for command-line **and** configuration file depending on build flags.
=> Strip out runtime-options depending on build flags

src/simpleconf_ftpd.h
I'm very sorry, I introduced this bug. The order of long runtime-option matters! Having `TLS` defined before ` TLSCipherSuite` will result in `syntax error line 123: [CipherSuite HIGH].` at server startup; obviously the "TLS" prefix gets cutted.
=> Order of configuration runtime-option matters

src/log_pgsql.c
This patch declares ```escaped_port``` within ```pw_pgscl_connect()``` in ```src/log_pgsql.c```,  and fixes the following compilation issue:
```
CC       libpureftpd_a-log_pgsql.o
In file included from ftpd.h:109:0,
from log_pgsql.c:7:
log_pgsql.c: In function ‘pw_pgsql_connect’:
log_pgsql.c:297:42: error: ‘escaped_port’ undeclared (first use in this function)
escaped_server, escaped_port, escaped_db,
```
=> Define escaped_port in pw_pgsql_connect()

src/ftp_parser.c, src/ftpd.c, src/globals.h
I'm not sure if this is the ideal way to fix this issue, if it introduces other issues, or if the current behaviour is preferred by the developers. 
The problem I am having is with blackbox firmware (Cisco IOS and other network vendors) pushing config to an FTP and expecting command pipelining to delay a QUIT until data transfers complete. They are simple clients that just blast commands and wait for sockets to close. Looking at RFC959, this is probably expected behaviour - it's not precisely stated. With current pure-ftpd, this results in aborting mid-transfer and truncated uploads. 
My assumption on the RFC appears to be matched by a few other FTP daemons I checked (vsftpd, proftpd and pyftpdlib), only pure-ftpd treated a QUIT like an immediate ABOR. 
This fix delays the reaction to a …
=> Allow QUIT during an active transfer to defer until transfer completes

README
I spent a bit of time scratching my head when my server kept saying "unknown command", so let's update the doc with a note.  I'd be glad to update the man page as well. 
Source: Frank via https://marc.info/?l=pureftpd-list&m=126044538824016&w=2
=> BrokenClientsCompatibility mode disables EPSV

src/ftpd.h
Reverts jedisct1/pure-ftpd#168
`HAVE_STRUCT_STATVFS` and `HAVE_STRUCT_STATVFS64` are not defined anywhere.
=> Revert "Alpine bugfix for storage size of 'statfsbuf' isn't known"

.github/workflows/codeql-analysis.yml
I've updated the actions according to following docs:
https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/
=> upgrade to the CodeQL Action v2

src/tls.c
After OpenSSL 1.1.0, ECDH is always enabled ( openssl/openssl#1437 ) and `EC_KEY_new_by_curve_name`, `EC_KEY_free` are deprecated in OpenSSL 3.0.
=> Improve OpenSSL API compatibility

src/ftpd.h
Increase the MAX_DATA_SIZE to accomodate yescrypt, which is now the default in some distros. This was discussed in https://forums.fedoraforum.org/showthread.php?332193-Problems-with-unix-authentication-in-pure-ftpd&p=1881101 . I also tested the fix myself. 32M is the smallest power of 2 size that works.
=> Fix unix login with yescrypt hashed passwords

src/messages_fr.h
Self-explanatory, correct conjugation in French is "peux", and not "peut".
=> fix: typo in french messages

src/ftp_parser.c
Hi, I recently ran into an issue with data connection in passive mode (I'm not sure if it couldn't be established or if it was interrupted), which caused the server to send "227 Logout." response.
However this response was being blocked by Linux's netfiter connection tracking FTP helper because it couldn't find a port number. This caused both sides to get stucked in unusual state (Client was stucked in `FIN-WAIT-1` and server in `LAST-ACK`).
This also printed dozens of messages like this into kernel log:
```
nf_ct_ftp: dropping packet: partial matching of `227 ' IN= OUT= SRC=192.168.88.11 DST=192.168.88.2 LEN=65 TOS=0x10 PREC=0x00 TTL=64 ID=21753 DF PROTO=TCP SPT=21 DPT=52558 SEQ=1495310752 ACK=1151444886 WINDOW=1019 RES=0x00 ACK PSH FIN URGP=0 OPT (0101080ACEAB6C79379C8674) 
nf_ct_ftp: …
```
=> fix: server sending "227 Logout." response

src/ls.c
In the domlsd() function of the ls.c file, this code: `!isspace((unsigned char) * base++)` does not check if the base pointer points to the end of the cmd buffer, so this error may cause the base pointer to cross the cmd buffer, resulting in out-of-bounds read errors.
There are POC scripts below that can cause out-of-bounds reads:
```python
from pwn import *
import sys
ip=sys.argv[1]
port=sys.argv[2]
p=remote(ip,port)
p.sendline(b"USER fuzzing")
p.sendline(b"PASS fuzzing")
#sending payload triggers the bug
payload=b"MLSD -".ljust(4110,b'.')
p.sendline(payload)
p.interactive()
```
The following image shows the base pointer before triggering the vulnerability, which points to the cmd buffer:
After executing the vulnerability point, the base pointer crosses the cmd buffer and points to other …
=> fix a bug of out-of-bounds reading in the domlsd() function in the ls.c

README.LDAP, src/log_ldap.c
The existing LDAP code allows an administrator to select the URI scheme used to connect to the LDAP server: either "ldap://" or "ldaps://".  However there exists an additional scheme "ldapi://" which was created by the authors of OpenLDAP ([See Here](https://datatracker.ietf.org/doc/html/draft-chu-ldap-ldapi)).  This allows a URI to be constructed that specifies a Unix domain socket to connect to on the filesystem.  
Coincidentally, the LDAP client library which pure-ftpd uses is libldap which is part of the OpenLDAP project.  The existing pure-ftpd LDAP code simply constructs an LDAP URI string and passes it directly to this library.  This _almost_ allows pure-ftpd servers to use the ldapi scheme as-is, but the existing code always appends a port number to the URI and ldapi URIs cannot …
=> Add support and documentation for "ldapi://"  URI scheme

src/log_ldap.c
*dn is '\0' if user not found and pw_ldap_connect will succeed when connect to active directory even dn is '\0'.
Should fail if user not found.
=> support active directory
